@baseUrl = http://localhost:3333
@session_token = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/account
Content-Type: application/json

{
  "name": "Teste",
  "password": "123456",
  "email": "teste@teste2.com.br"
}

###

# @name authenticate
POST {{baseUrl}}/session
Content-Type: application/json

{
  "email": "teste@teste.com.br",
  "password": "123456"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{session_token}}

{
  "title": "New Question 21",
  "content": "Content of the question"
}

###
# @name fetch_all_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{session_token}}